import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { lazy } from 'react'
const inter = Inter({ subsets: ['latin'] })


const Header  = lazy(() => import('@/components/Header'));
const Footer  = lazy(() => import('@/components/Footer'));
export const metadata: Metadata = {
  title: 'NFT',
  description: 'Generated by NFT',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + " "  + "p-2 bg-[#16091B]"}>
        <Header />
          { children }
        <Footer />
      </body>
    </html>
  )
}
